name: My Secret Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
    steps:
      - name: My secret
        run: echo "My secret is ${{ secrets.API_KEY }}"
