name: My Secret Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My secret API
        run: echo "My secret is ${{ secrets.API_KEY }}"
      - name: My_Secret
        run: echo "My_secret is ${{ secrets.MY_SECRET }}"
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
          print(q)
        shell: python
  secrets-in-GH:
     runs-on: windows-latest
     steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g' 
        
