name: secret demo

on:
  push:
    branches:
      - main

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        uses: actions/checkout@v2
        
      - name: Set GH_TOKEN environment variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Secret
        run: |
          echo "NewSecretValue" | gh secret set MY_SECRET --repo Rafi98/GH_Actions


      

