name: secret demo

on:
  push:
    branches:
      - main

jobs:
  secret_job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set GH_TOKEN environment variable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      

