name: secret demo

on:
  push:
    branches:
      - main

jobs:

  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "Secret value is $MY_SECRET"

  Print-secret-value:
      runs-on: ubuntu-latest
      steps:
      - name: Set env as secret
        env:
         MY_VAL: ${{ secrets.MY_SECRET }}
         run: |
           import os
           for q in (os.getenv("MY_VAL")):
             print(q)
         shell: python





  secret_job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set GH_TOKEN environment variable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

 

  update-secrets-and-trigger:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Update Secrets
        run: |
         gh secret set MY_VALUE --repos=GH_Actions 
          # GitHub CLI to update secrets
              echo "NewSecretValue" 
              gh secret set MY_VALUE --repos=Rafi98/GH_Actions/ --visibility=all
      - name: Trigger Main Workflow
        run: |
          # GitHub CLI to trigger a workflow
            gh workflow run secret_demo.yml --ref main --repository Rafi98/GH_Actions --inputs trigger_reason="Secret updated"


      

