name: Use Decrypted Value

on:
  workflow_dispatch:
    inputs:
      decrypted_value:
        description: 'Decrypted value'
        required: true

jobs:
  use_decrypted_value:
    runs-on: ubuntu-latest
    steps:
      - name: Use Decrypted Value
        run: |
          # Store the decrypted value in an environment variable
          export MY_SECRET="${{ github.event.inputs.MY_SECRET }}"
          
          # Use the decrypted value in subsequent steps
          echo "Decrypted value: $MY_SECRET"
