name: Use Decrypted Value

on:
  workflow_dispatch:
    inputs:
      decrypted_value:
        description: 'Decrypted value'
        required: true

jobs:
 encrypt_decrypt_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install GPG
      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install -y gnupg
  
      - name: Import GPG Private Key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
