name: secret demo

on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Secret Demo!"
     #Printing secret
      - name: Print Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "My secret is $MY_SECRET"
