name: Update Secret

on:
  workflow_dispatch:

jobs:
 print-secrets:
   runs-on: ubuntu-latest
   steps:
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python

 update_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gh
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Update secret value
        run: |
          echo "$NEW_SECRET_VALUE" | gh secret set MY_SECRET_NAME
        env:
          NEW_SECRET_VALUE: ${{ secrets.NEW_SECRET_VALUE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
