name: secret demo

on:
  push:
    branches:
      - main

jobs:
  secret_job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set GH_TOKEN environment variable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  update-secrets-and-trigger:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Update Secrets
        run: |
          # GitHub CLI to update secrets
              echo "NewSecretValue" | gh secret set MY_VALUE --repos=Rafi98/GH_Actions --visibility=private
      - name: Trigger Main Workflow
        run: |
          # GitHub CLI to trigger a workflow
            gh workflow run secret_demo.yml --ref main --repository Rafi98/GH_Actions --inputs trigger_reason="Secret updated"


      

