name: secret demo

on:
  push:
    branches:
      - main

jobs:
 print-secrets:
   runs-on: ubuntu-latest
   steps:
    #  - name: Print a message
     #   run: echo "Secret Demo!"
     #Printing secret
      #- name: Print Secret
       # env:
        #  MY_SECRET: ${{ secrets.MY_SECRET }}
        #run: echo "My secret is $MY_SECRET" 
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python

 #dynamic-secret-injection:
  #  runs-on: ubuntu-latest
   # env:
    #  DYNAMIC_SECRET: ${{ secrets.MY_SECRET }} # Setting the environment variable with the secret value
    #steps:
     # - name: Print Dynamic Secret
      #  run: echo "Dynamic secret value $DYNAMIC_SECRET"

 update-secrets-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Update Secrets
        run: |
          # Example using GitHub CLI to update secrets
              echo "NewSecretValue" | gh secret set MY_VALUE --repository=Rafi98/GH_Actions --visibility=private
      - name: Trigger Main Workflow
        run: |
          # Example using GitHub CLI to trigger a workflow
          #gh workflow run main.yml --ref main --repository owner/repo --inputs trigger_reason="Secret updated"
          gh workflow run main.yml --ref main --repository Rafi98/GH_Actions --inputs trigger_reason="Secret updated"
