name: secret demo

on:
  push:
    branches:
      - main

jobs:

  print-secrets:
   runs-on: ubuntu-latest
   steps:
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python


  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "Secret value is $MY_SECRET"

  display-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Display Secret Value
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Value of MY_SECRET: $MY_SECRET"


  update-secrets-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        uses: actions/checkout@v2
        
      - name: Set up GitHub CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set GH_TOKEN environment variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Secret
        run: |
          echo "new_secret_value" | gh secret set MY_SECRET --repo Rafi98/GH_Actions
          
      - name: Trigger Main Workflow
        run: |
          #gh workflow run main.yml --ref main --repo owner/repo --inputs trigger_reason="Secret update"
          gh workflow run secret_demo.yml --ref main --repo Rafi98/GH_Actions --inputs trigger_reason="Secret update"






  
