name: Update Secret

on:
  workflow_dispatch:

jobs:
 print-secrets:
   runs-on: ubuntu-latest
   steps:
      - name: Secret_Value
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python

 install-gh:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Allow the workflow to read repository contents
      actions: write   # Allow the workflow to interact with GitHub Actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your repository's code

      - name: Install gh CLI
        run: |
          # Install gh CLI
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh


      - name: Install gh CLI
        run: |
          # Install gh CLI
          sudo mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Update secret value
        run: |
          echo "$MY_SECRET" | gh secret set MY_SECRET
        env:
          MY_SECRET: ${{ secrets.NEW_SECRET_VALUE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
