name: Update Secret

on:
  workflow_dispatch:

jobs:
 print-secrets:
   runs-on: ubuntu-latest
   steps:
      - name: Secret_Value
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python

 login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh auth login --with-token <<<"${GH_TOKEN}"
          
