name: secret demo

on:
  push:
    branches:
      - main

jobs:

  print-secrets:
   runs-on: ubuntu-latest
   steps:
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python


  update-secrets-and-trigger:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Update Secrets
        run: |
         gh secret set MY_VALUE --repo Rafi98/GH_Actions
          # GitHub CLI to update secrets
              echo "NewSecretValue" 
              gh secret set MY_VALUE --repos=Rafi98/GH_Actions --visibility=all
      - name: Trigger Main Workflow
        run: |
          # GitHub CLI to trigger a workflow
            gh workflow run secret_demo.yml --ref main --repository Rafi98/GH_Actions --inputs trigger_reason="Secret updated"

  
