name: My Secret change workflow

on:
  push:
    branches:
      - main

jobs:
  #Before changing secrets values
  Before_Change_Secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Secrets_Before_Change
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
