name: Use Decrypted Value

on:
  workflow_dispatch:
    inputs:
      decrypted_value:
        description: 'Decrypted value'
        required: true

jobs:
  use_decrypted_value:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG Private Key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
